---
title: Land Ho
timezone: Europe/Rome
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Works
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/work/:title/"
    size: large
    thumbnail_image_file: 
    thumbnail_video_file: 
    video: 
    client: 
    payoff: 
    kind:
    - 
    year_date: 
    link: 
    grid:
    - size: half
      image_file: 
      video_file: 
email: hello@landhostudio.com
description: An awesome description of our new site
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalink: pretty
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- ".editorconfig"
