---
title: Land Ho
timezone: Europe/Rome
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Works
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: hello
  values:
    layout: hello
    columns:
    - title: 
      text: 
- scope:
    path: posts
  values:
    layout: posts
    showcase:
    - title: 
      link: 
      image_file: 
      video_file: 
    quotes:
    - quote: 
      author: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/work/:title/"
    position: 
    size: large
    thumbnail_image_file: 
    thumbnail_video_file: 
    video: 
    client: 
    payoff: 
    kind:
    - 
    collaborations:
    - 
    year_date: 
    link: 
    grid:
    - grid_size: large
      image_file: 
      video_file: 
      is_video_audio: false
      is_video_autoplay: false
    work:
    - 
email: hello@landhostudio.com
description: An awesome description of our new site
footer:
- title: Family
  text: |-
    Ci incontriamo tutti i giorni al
    [Loft Coho, Via Vertumno 2c 00157 Rome, Italy](https://maps.google.com/maps?q=Coho\+Loft\+in\+Rome\+Vertumno\+2\+c,\+00157\+Rome,\+Italy)
- title: Keep in touch
  text: |-
    T. [(\+39) 347 08 74 994](tel:\+393470874994)

    T. [(\+39) 320 07 55 112](tel:\+393200755112)

    M. [hello@landhostudio.com](mailto:hello@landhostudio.com)
- title: Hello
  text: Land Ho è il nostro progetto creativo che crede nel metodo e nella ricerca
    costante. Nasciamo nel 2014. Siamo una famiglia.
baseurl: "/new"
url: 
markdown: kramdown
permalink: pretty
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: 
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- ".editorconfig"
- src
- gulpfile.js
- package.json
- README.md
- node_modules
- webpack.config.js
