---
title: Land Ho
timezone: Europe/Rome
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Works
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: pages
  values:
    layout: hello
    columns:
    - title: 
      text: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/work/:title/"
    position: 
    size: large
    thumbnail_image_file: 
    thumbnail_video_file: 
    video: 
    client: 
    payoff: 
    kind:
    - 
    year_date: 
    link: 
    grid:
    - size: half
      image_file: 
      video_file: 
      is_video_audio: false
email: hello@landhostudio.com
description: An awesome description of our new site
footer:
- title: Family
  text: |-
    Ci incontriamo tutti i giorni al
    [Loft Coho, Via Vertumno 2c 00157 Rome, Italy](https://maps.google.com/maps?q=Coho\+Loft\+in\+Rome\+Vertumno\+2\+c,\+00157\+Rome,\+Italy)
- title: Keep in touch
  text: |-
    T. [(\+39) 347 08 74 994](tel:\+393470874994)

    T. [(\+39) 320 07 55 112](tel:\+393200755112)

    M. [hello@landhostudio.com](mailto:hello@landhostudio.com)
- title: Hello
  text: Land Ho è il nostro progetto creativo che crede nel metodo e nella ricerca
    costante. Nasciamo nel 2014. Siamo una famiglia.
baseurl: 
url: 
markdown: kramdown
permalink: pretty
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: 
gems:
- jekyll-feed
- jekyll-paginate
<<<<<<< HEAD
<<<<<<< HEAD
=======
source: ./src
destination: ./dist
>>>>>>> parent of 15f2181... Normalize Jekyll structure to default for Siteleaf compatibility
exclude:
- "_scripts"
- "_stylesheets"
<<<<<<< HEAD
- ".editorconfig"
- "gulpfile.js"
- "package.json"
- "README.md"
- "node_modules"
- "webpack.config.js"
=======
source: "./src"
destination: "./dist"
exclude:
- _scripts
- _stylesheets
>>>>>>> origin/master
=======
>>>>>>> parent of 15f2181... Normalize Jekyll structure to default for Siteleaf compatibility
